### ISSUE TITLE
Can't get SNP info with wrapper, but it works on site.

### ISSUE THREAD

**Issue by Arkkienkeli** [biothings/myvariant.py#5]
```
mv = myvariant.MyVariantInfo()
your_rsid_list = ['rs121908746']
mv.getvariant('rs121908746')
res = mv.querymany(list(set(your_rsid_list)), scopes='dbsnp.rsid', fields='clinvar')
```

`1 input query terms found no hit:
	['rs121908746']
`
If I query this SNP on site, I get full response on it.
Python 3.5.2

**Comment by cyrus0824** [comment]
Hi, thanks for your comment.

The reason why this query doesn't work is because this variant is not listed in our database as a dbsnp variant.  When you query our site, I assume you are doing something like:

http://myvariant.info/v1/query?q=rs121908746

This does indeed return the correct variant, because it queries the "_all" field (an aggregation of several important fields inside the variant, including clinvar.rsid).  But if you explore the variant, by restricting the fields to dbsnp as in:

http://myvariant.info/v1/query?q=rs121908746&fields=dbsnp

you'll notice there is no dbsnp field for this variant...  Therefore, when you do your querymany with scopes='dbsnp.rsid', it's looking for a variant with dbsnp.rsid=rs121908746 - which doesn't exist (I will consult our data loading expert to figure out why, stay tuned for more on this...)

In the meantime, you can change your scopes to clinvar.rsid and find this variant, or if you want to query a list of many rsids and don't know which db it might be in, you can use a list for scopes.  See this example:

`In [1]: import myvariant

In [2]: mv = myvariant.MyVariantInfo()

In [3]: your_rsid_list = ['rs121908746']

In [4]: res = mv.querymany(list(set(your_rsid_list)), scopes=['dbsnp.rsid', 'clinvar.rsid'], fields='clinvar')
querying 1-1...done.
Finished.

In [5]: res
Out[5]: 
[{'_id': 'chr7:g.117232273del',
  '_score': 15.91139,
  'clinvar': {'_license': 'https://goo.gl/OaHML9',
   'allele_id': 47057,
   'alt': '-',
   'chrom': '7',
   'cytogenic': '7q31.2',
   'gene': {'id': '1080', 'symbol': 'CFTR'},
   'hg19': {'end': 117232273, 'start': 117232273},
   'hg38': {'end': 117592219, 'start': 117592219},
   'hgvs': {'coding': 'NM_000492.3:c.2052delA',
    'genomic': ['NC_000007.13:g.117232273delA',
     'NC_000007.14:g.117592219delA',
     'NG_016465.4:g.131436delA']},
   'rcv': {'accession': 'RCV000043563',
    'clinical_significance': 'Pathogenic',
    'conditions': {'identifiers': {'medgen': 'C0010674',
      'omim': '219700',
      'orphanet': '586'},
     'name': 'Cystic fibrosis (CF)'},
    'last_evaluated': '2004-03-03',
    'number_submitters': 4,
    'origin': 'germline',
    'preferred_name': 'NM_000492.3(CFTR):c.2052delA (p.Lys684Asnfs)',
    'review_status': 'practice guideline'},
   'ref': 'A',
   'rsid': 'rs121908746',
   'type': 'Deletion',
   'variant_id': 38493},
  'query': 'rs121908746'}]
`
I hope this helps, and I'll get back to you regarding the dbsnp field for this variant...

**Comment by newgene** [comment]
Verified this data issue with dbSNP has already been fixed.
