### ISSUE TITLE
'str' instead of 'dict' while returnall=True

### ISSUE THREAD

**Issue by Arkkienkeli** [biothings/myvariant.py#6]
Hi. When I use option `returnall=True` in my query, I get string type of response, not dictionary.
This works fine:
```
res = mv.querymany(list(set(your_rsid_list)), scopes=['dbsnp.rsid', 'clinvar.rsid'], fields='clinvar')
for r in res:
	print(type(r))
```
`<class 'dict'>`

This fails:
```
res = mv.querymany(list(set(your_rsid_list)), scopes=['dbsnp.rsid', 'clinvar.rsid'], fields='clinvar', returnall=True)
for r in res:
	print(type(r))
```
`<class 'str'>`

Thank you for attention.

**Comment by kevinxin90** [comment]
Hi Nick,

There is no 'returnall' parameter for the client. You should use 'fetchall=True'.

Thanks!
Kevin

**Comment by Arkkienkeli** [comment]
Thank you.
It is pretty confusing that in docs stated
> returnall – if True, return a dict of all related data, including dup. and missing qterms

**Comment by Arkkienkeli** [comment]
I am not sure if I should open another issue for this, but:
```
2 input query terms found no hit:
	['rs80357713', 'rs80359716']
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
```
I used both scopes (clinvar and dbsnp),  API returns no hit (but these SNPs are in Clinvar) and prompts me that I should use  `returnall=True` flag. Is is a combination of previous and current issues :)
Thanks!

**Comment by kevinxin90** [comment]
@Arkkienkeli 
Oh, my bad. 'returnall' is a valid parameter in myvariant python client. 
But what 'returnall' returns is a dictionary with three keys, e.g. dup (which means duplicate terms), 'missing' (which means missing terms) and 'out'(which means output). 
So I saw ur code:
`for r in res:
	print(type(r))`
Since 'res' is a dict object, your code is only going to fetch u these dict keys. That's why the type of r is string. You should just print out the res instead. 
For the second question, regarding the rsid missing you point out. I double checked on dbsnp, these are already deprecated rsids. For example,  rs80359716 has merged into rs80359714. If you are sure they exists in ClinVar, could you give me the corresponding ClinVar accession number for me to look into it, e.g. something like RCV000000606.

Thanks!

**Comment by Arkkienkeli** [comment]
For rs80357713 - https://www.ncbi.nlm.nih.gov/clinvar/variation/17662/, there a lot of entries, for example SCV000282348.1 
For rs80359716 - https://www.ncbi.nlm.nih.gov/clinvar/variation/9328/, SCV000301287.2 (and more)
